---
- name: Install Minecraft Server
  hosts: instances

  tasks:
    - name: Update and upgrade apt
      apt:
        update_cache: true
        upgrade: true

    - name: Install java
      apt:
        name: default-jre
        state: present

    - name: Download server
      get_url:
        url: https://piston-data.mojang.com/v1/objects/145ff0858209bcfc164859ba735d4199aafa1eea/server.jar
    
    - name: Install server
      command: java -Xmx1024M -Xms1024M -jar minecraft_server.1.20.6.jar nogui